;;; amble-edit.el --- Transactional versioned edits -*- lexical-binding: t; -*-
(require 'amble-core)

(defun amble-edit--plan (changes)
  "Validate CHANGES completely before any buffer is modified."
  (let (plan buffers (total 0))
    (unless (and (vectorp changes) (<= 1 (length changes) 20))
      (user-error "Provide 1–20 buffer change groups"))
    (dolist (change (append changes nil))
      (let ((buffer (amble--target change))
            (edits (append (alist-get 'edits change) nil)))
        (when (memq buffer buffers) (user-error "Combine edits for a buffer into one group"))
        (push buffer buffers)
        (with-current-buffer buffer
          (unless (equal (alist-get 'expected_tick change) (buffer-chars-modified-tick))
            (user-error "Buffer %s changed; read it again before editing" (buffer-name)))
          (when buffer-read-only (user-error "Buffer %s is read-only" (buffer-name)))
          (unless (and edits (<= (length edits) 100)) (user-error "Provide 1–100 edits per buffer"))
          (setq edits (sort (copy-sequence edits) (lambda (a b) (< (alist-get 'start a) (alist-get 'start b)))))
          (let ((last-end nil) (last-start nil))
            (dolist (edit edits)
              (let ((start (alist-get 'start edit)) (end (alist-get 'end edit)) (text (alist-get 'text edit)))
                (unless (and (integerp start) (integerp end) (stringp text)
                             (<= (point-min) start end (point-max)))
                  (user-error "Invalid edit range or replacement in %s" (buffer-name)))
                (when (and last-end (or (< start last-end) (= start last-start)))
                  (user-error "Overlapping edits are ambiguous"))
                (cl-incf total (+ (length text) (- end start)))
                (when (> total 96000) (user-error "Edit batch exceeds 96000 characters; split it"))
                (setq last-start start last-end end)))))
        (push (cons buffer edits) plan)))
    (nreverse plan)))

(defun amble-edit-tool (args)
  "Preview, apply or undo version-checked edits described by ARGS."
  (if (equal (alist-get 'action args) "undo")
      (with-current-buffer (amble--target args)
        (unless (equal (alist-get 'expected_tick args) (buffer-chars-modified-tick))
          (user-error "Buffer changed; read before undo"))
        (when (or buffer-read-only (eq buffer-undo-list t)) (user-error "This buffer cannot be undone"))
        (amble--execute (lambda () (undo-only 1)))
        (append (amble--buffer-info (current-buffer)) `((tick . ,(buffer-chars-modified-tick)) (saved . :false))))
    (unless (member (alist-get 'action args) '("preview" "apply")) (user-error "Unknown edit action"))
    (let* ((plan (amble-edit--plan (alist-get 'changes args)))
           (preview (equal (alist-get 'action args) "preview")))
      (if preview
          (let ((buffer (get-buffer-create "*amble-edit-preview*")))
            (with-current-buffer buffer
              (let ((inhibit-read-only t))
                (erase-buffer)
                (insert "Edit preview — no changes applied\n\n")
                (dolist (entry plan)
                  (insert (format "%s\n" (buffer-name (car entry))))
                  (dolist (edit (cdr entry))
                    (insert (format "Positions %d..%d\nBefore:\n%s\nAfter:\n%s\n\n"
                                    (alist-get 'start edit) (alist-get 'end edit)
                                    (with-current-buffer (car entry)
                                      (buffer-substring-no-properties (alist-get 'start edit) (alist-get 'end edit)))
                                    (alist-get 'text edit)))))
                (goto-char (point-min)) (special-mode)))
            (display-buffer buffer)
            `((preview . t) (buffer . ,(buffer-name buffer))
              (targets . ,(vconcat (mapcar (lambda (entry) (buffer-name (car entry))) plan)))))
        (let ((ticks (mapcar (lambda (entry)
                               (with-current-buffer (car entry)
                                 (cons (current-buffer) (buffer-chars-modified-tick)))) plan))
              groups success)
          (unwind-protect
              (progn
                (dolist (entry plan)
                  (with-current-buffer (car entry)
                    (when (eq buffer-undo-list t) (buffer-enable-undo))
                    (undo-boundary)
                    (let ((group (prepare-change-group)))
                      (push (cons (current-buffer) group) groups)
                      (activate-change-group group))))
                (dolist (entry plan)
                  (with-current-buffer (car entry)
                    (unless (= (cdr (assq (current-buffer) ticks)) (buffer-chars-modified-tick))
                      (user-error "A hook changed %s during the batch; rolling back" (buffer-name)))
                    (save-excursion
                      (dolist (edit (reverse (copy-sequence (cdr entry))))
                        (goto-char (alist-get 'start edit))
                        (delete-region (point) (alist-get 'end edit))
                        (insert (alist-get 'text edit))))))
                (setq success t))
            (dolist (entry groups)
              (with-current-buffer (car entry)
                (if success (accept-change-group (cdr entry)) (cancel-change-group (cdr entry)))
                (undo-boundary))))
          `((applied . t) (saved . :false) (undoable . t)
            (buffers . ,(vconcat
                         (mapcar (lambda (entry)
                                   (with-current-buffer (car entry)
                                     `((buffer . ,(buffer-name)) (tick . ,(buffer-chars-modified-tick))
                                       (edits . ,(length (cdr entry))) (modified . ,(if (buffer-modified-p) t :false)))))
                                 plan)))))))))

(provide 'amble-edit)
;;; amble-edit.el ends here
