;;; amble-zk-tests.el --- Local integration tests -*- lexical-binding: t; -*-
(require 'ert)
(unless noninteractive (error "Run these tests in batch Emacs"))
(require 'cl-lib)
(defvar zk-root)
(defvar zk-inbox-file)
(defvar zk-agenda-file)
(defvar zk--previous-agenda-files)
(defvar zk-dashboard--metadata-cache)
(defvar zk-dashboard-buffer-name)
(defvar zk-dashboard--refresh-timer)
(defvar org-agenda-files)
(declare-function zk-list-tasks "zk")
(defmacro amble-test-with-zk (&rest body)
  `(let* ((root (make-temp-file "amble-zk-test-" t))
          (zk-root (file-name-as-directory root))
          (zk-inbox-file (expand-file-name "my-inbox.org" root))
          (zk-agenda-file (expand-file-name "my-agenda.org" root))
          (zk--previous-agenda-files nil)
          (org-agenda-files nil)
          (zk-dashboard--metadata-cache (make-hash-table :test #'equal)))
     (unwind-protect
         (progn (require 'zk) ,@body)
       (when (and (boundp 'zk-dashboard--refresh-timer) (timerp zk-dashboard--refresh-timer))
         (cancel-timer zk-dashboard--refresh-timer))
       (dolist (buffer (buffer-list))
         (with-current-buffer buffer
           (when (or (and (boundp 'zk-dashboard-buffer-name)
                          (equal (buffer-name) zk-dashboard-buffer-name))
                     (and buffer-file-name (file-in-directory-p buffer-file-name root)))
             (set-buffer-modified-p nil) (kill-buffer buffer))))
       (delete-directory root t))))
(require 'amble-zk)
(require 'amble-org)

(ert-deftest amble-zk-captures-and-updates-via-shared-files ()
  (amble-test-with-zk
   (let ((amble-tools--enabled '("zk")))
     (let ((result (amble-dispatch-tool "emacs_zk" '((action . "add_task") (title . "Read")
                                                    (scheduled . "2026-10-02")))))
       (should (equal zk-inbox-file (alist-get 'file result))))
     (let* ((listed (amble-dispatch-tool "emacs_zk" '((action . "tasks"))))
            (task (aref (alist-get 'tasks listed) 0)))
       (amble-dispatch-tool "emacs_zk"
                            `((action . "update_task") (file . ,(alist-get 'file task))
                              (point . ,(alist-get 'point task)) (expected_tick . ,(alist-get 'tick task))
                              (state . "NEXT")))
       (should (equal "NEXT" (plist-get (car (zk-list-tasks)) :state))))
     (let ((plan (amble-dispatch-tool "emacs_zk" '((action . "add_plan") (title . "Plan") (body . "Notes")))))
       (should (equal zk-agenda-file (alist-get 'file plan)))))))

(ert-deftest amble-old-todo-entry-delegates-to-zk ()
  (amble-test-with-zk
   (should-not (boundp 'amble-todo-file))
   (amble-add-todo "Through zk")
   (should (= 1 (length (zk-list-tasks))))
   (should-error (amble-add-todo "Elsewhere" (expand-file-name "other.org" zk-root)) :type 'user-error)
   (should-not (assq 'todo_file (amble-org-tool '((action . "templates")))))))

(ert-deftest amble-zk-is-optional-and-reports-missing-package ()
  (let ((real-require (symbol-function 'require)))
    (cl-letf (((symbol-function 'require)
               (lambda (feature &optional filename noerror)
                 (unless (eq feature 'zk) (funcall real-require feature filename noerror)))))
      (should-error (amble-zk-tool '((action . "info"))) :type 'user-error))))

(ert-deftest amble-discovers-zk-in-a-loaded-session ()
  (amble-test-with-zk
   (let ((amble-tools--enabled nil) (amble-origin-buffer nil))
     (amble-tools-select-context)
     (should (member "zk" amble-tools--enabled))
     (should (seq-some (lambda (spec) (equal (alist-get 'name spec) "emacs_zk"))
                       (append (amble-tool-specs) nil))))))

(provide 'amble-zk-tests)
